#!/bin/bash

# Description:
# Compile a provided Solution file.
#
# Parameters:
# $1: Directory where file-to-run lives.
# $2: Solution file name with extension (e.g. Solution.java).
#
# Example invocation:
# ./src/shell/compile . Solution.java

# Base path of the script
BASE_PATH=$(dirname "$0")

# Imports
source "$BASE_PATH"/_command

entry_file=$2
entry_file_name=$(echo $2 | cut -d'.' -f1)

# Execute entry file with standard input
case $entry_file in
  *.java) #.class
    command_is_required javac
    javac $1/${entry_file}
    ;;
  *.c)    # .out
    command_is_required gcc
    gcc $1/${entry_file} -o "$1/${entry_file_name}.out"
    ;;
  *.cpp)  # .out
    command_is_required g++
    g++ $1/${entry_file} -o "$1/${entry_file_name}.out"
esac
