#!/bin/bash

# Description:
# Provided a command name, print an error message if the command
# is not available and exit with 1. Else, just exit with 0.
#
# Parameters:
# $1: Name of the command.
#
# Output (stdout):
# 'true' when the command is available.
# 'false' when the command is NOT available.
#
# Example invocation:
# ./src/shell/has-command ghc

# If command is found, print 'true'
command -v $1 > /dev/null 2>&1 && { echo true; exit 0; }

# Else, print 'false'
echo false
