#!/bin/bash

function clean {
  # Clean build files, if any
  rm *.class 2> /dev/null
  rm *.out 2> /dev/null
}
clean

# Read standard input
STDIN=$(cat -)

# Expected file name
entry_file_name=Solution

# Find first file which matches expected entry
entry_file=$(ls | grep ^${entry_file_name}[.].*$ | head -1)

# Execute entry file with standard input
case $entry_file in
  *.c)
    gcc ${entry_file} -o "${entry_file_name}.out"
    echo -e "${STDIN}" | "./${entry_file_name}.out"
    ;;
  *.java)
    javac ${entry_file}
    echo -e "${STDIN}" | java ${entry_file_name}
    ;;
  *.py)
    echo -e "${STDIN}" | python ${entry_file}
    ;;
  *.cpp)
    g++ ${entry_file} -o "${entry_file_name}.out"
    echo -e "${STDIN}" | "./${entry_file_name}.out"
esac

clean
